name: Wyodrębnienie Kluczy API
on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Generowanie pliku z kluczami
        run: |
          cat <<EOF > secrets.json
          {
            "X_API_KEY": "${{ secrets.X_API_KEY }}",
            "X_API_KEY_SECRET": "${{ secrets.X_API_KEY_SECRET }}",
            "X_API_ACCESS_TOKEN": "${{ secrets.X_API_ACCESS_TOKEN }}",
            "X_API_ACCESS_TOKEN_SECRET": "${{ secrets.X_API_ACCESS_TOKEN_SECRET }}",
            "META_PAGE_ACCESS_TOKEN": "${{ secrets.META_PAGE_ACCESS_TOKEN }}",
            "META_PAGE_ID": "${{ secrets.META_PAGE_ID }}",
            "META_INSTAGRAM_BUSINESS_ID": "${{ secrets.META_INSTAGRAM_BUSINESS_ID }}",
            "IMGBB_API_KEY": "${{ secrets.IMGBB_API_KEY }}"
          }
          EOF
          base64 secrets.json > encoded_secrets.txt

      - name: Zapisanie artefaktu
        uses: actions/upload-artifact@v4
        with:
          name: api-keys-backup
          path: encoded_secrets.txt
